### ISSUE TITLE
Add environment variables into task.yaml

### ISSUE THREAD

**Issue by Daegalus** [sonm-io/core#114]
I am currently working on getting a CS:GO server up and running with Sonm. I have the docker container working, and it actually works in Sonm, but I can't properly pass in some variables to make it work 100%.

CS:GO server requires a Steam Token to work in non-lan mode. When I run docker normally, I used `-e GSLT=<token>` to pass it in. or I pass it in as part of the command `docker run csgo /home/csgoserver/start.sh <token>`

Either of these methods would work, but not currently possible with the tasks yaml. I looked through the code, and it seems you have tests for a `command` config value in the tasks yaml, but it is not hooked up or get passed into the container configs in insomnia. As for ENV the only place I see that is in Exec for the overseer or ExecCmd in the container. Neither of which seem to be used fro the tasks yaml method of launching.

Could we get ENV variables hooked up? I can try to submit a pull request myself, but I haven't had time to familiarize myself with the code, so it might be a while before I can comfortably provide a pull request.

Example env config:
```yaml
task:
  container:
    # image name to start, requried
    name: daegalus/docker-csgo:latest
    env:
      - "GSLT=<token>"
      - "GAMEPORT=27015"
  resources:
      # number of CPU cores required by task, required param
      CPU: 1
      # amount of memory required by task, required param
      # You may use Kb, Mb and Gb suffixes
      RAM: 50Mb
```

https://docs.docker.com/engine/api/v1.29/#operation/ContainerCreate (Env)
