### ISSUE TITLE
Can't start worker, "error": "invalid Ethereum address format"

### ISSUE THREAD

**Issue by walkjivefly** [sonm-io/core#369]
I'm following the Getting Started instructions for example for supplier for linux. Steps 1-5 work 5, in step 6 I modify the worker.yaml as
```
...
ethereum:
  # path to keystore
  key_store: "/home/sonm/keys"
  # passphrase for keystore
  pass_phrase: "xxxxxxxxxxxxx"

# locator service allows nodes to discover each other
locator:
  # locator gRPC endpoint, required
  #endpoint: "my_ether_address_here@myip:port"
  endpoint: "my_ether_address_here@139.59.250.244:9090"
```

At step 7 the worker refuses to start. The error is
```
...
2018-01-02T23:35:08.460Z        FATAL   miner/main.go:69        failed to create a new Miner    {"error": "invalid Ethereum address format", "errorVerbose": "invalid Ethereum address format\ngithub.com/sonm-io/core/util.ParseEndpoint\n\t/root/go/src/github.com/sonm-io/core/util/grpcsecure.go:158\ngithub.com/sonm-io/core/insonmnia/miner.(*MinerBuilder).getHubConnectionInfo\n\t/root/go/src/github.com/sonm-io/core/insonmnia/miner/builder.go:236\ngithub.com/sonm-io/core/insonmnia/miner.(*MinerBuilder).Build\n\t/root/go/src/github.com/sonm-io/core/insonmnia/miner/builder.go:135\nmain.main\n\t/root/go/src/github.com/sonm-io/core/cmd/miner/main.go:67\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:195\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337"}
github.com/sonm-io/core/vendor/go.uber.org/zap.Stack
        /root/go/src/github.com/sonm-io/core/vendor/go.uber.org/zap/field.go:209
github.com/sonm-io/core/vendor/go.uber.org/zap.(*Logger).check
        /root/go/src/github.com/sonm-io/core/vendor/go.uber.org/zap/logger.go:273
github.com/sonm-io/core/vendor/go.uber.org/zap.(*Logger).Fatal
        /root/go/src/github.com/sonm-io/core/vendor/go.uber.org/zap/logger.go:208
main.main
        /root/go/src/github.com/sonm-io/core/cmd/miner/main.go:69

```

I've tried with a Rinkeby address created by MyEthereumWallet and an address created by the sonm wallet. I've tried with and without the leading 0x on the address. I've tried with my IP address and the IP address already in the sample worker.yaml. I've tried different port numbers. I've opened the ports in my firewall.

Obviously I'm doing something incredibly stupid but I can't see what. An Ethereum address is an Ethereum address and I can't see why it doesn't like mine.
