### ISSUE TITLE
Auto select miner based on devices wish-list

### ISSUE THREAD

**Issue by 3Hren** [sonm-io/core#66]
This requires some specification attached to the application. Like (simplified):

```yaml
hardware:
  cpu: [Intel Core i5, Intel Core i7]
  gpu: [NVIDIA Tesla]
```
